
WITH 
SCASSFAT AS (
SELECT * FROM [20.82.75.6].TARI.dbo.C19SCASSFAT WHERE CODCLI='{0}'
),
M_STFA_M AS (
SELECT * FROM [20.82.75.6].TARI.dbo.C19M_STFA_M WHERE CODCLI='{0}'
),
FCAVVPAG AS (
SELECT * FROM [20.82.75.6].TARI.dbo.C19FCAVVPAG WHERE CODCLI='{0}'
),
FCCLIFAT AS (
SELECT * FROM [20.82.75.6].TARI.dbo.C19FCCLIFAT WHERE CODCLI='{0}'
),
SSCADFAT AS (
SELECT * FROM [20.82.75.6].TARI.dbo.C19SSCADFAT WHERE CODCLI='{0}'
)

SELECT CAST(0 AS bigint) as Id,A.CODCLI CodCli,A.NUMCONT NumCont,A.ANNORIF AnnoRif,A.CODICE_TRIBUTO CodTributo,CAST(A.DA_PAGARE AS float) DaPagare,CAST(A.PAGATO AS float) Pagato,CAST(A.SALDO AS float) Saldo,
B.RAGSO RagSo,B.INDIRIZZO Indirizzo,B.CF CodFis,B.DTFAT DtFat,B.NUMFAT NumFat, B.NUM_AVVISO NumAvviso, CAST(0 as bit) Disabled
FROM 
(SELECT TRIM(S1.CODCLI) CODCLI, TRIM(S1.NUMCONT) NUMCONT, S1.ANNORIF, S1.CODICE_TRIBUTO,
    SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI) as DA_PAGARE,
    case when ((s1.annorif > 2013) or (MAX(s1.tipoavviso) = 'L')) then round( SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI),0)
    ELSE SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI)   end   AS DA_PAGAREN,
    MAX(S1.PAGATO) as PAGATO,
    case when s1.annorif = 2013 then MAX(S1.PAGATO)
    else  round(MAX(S1.PAGATO),0) end  AS PAGATON,
    (SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) AS SALDO,
    case when ((s1.annorif > 2013) or (MAX(s1.tipoavviso) = 'L')) then round((SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) ,0)
    Else (SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) END AS SALDON

FROM
    (SELECT B.CODCLI, B.NUMCONT, '3944' AS CODICE_TRIBUTO, B.ANNORIF AS ANNORIF,
        ( SELECT A1.TIPOAVVISO FROM  M_STFA_M A1
        WHERE B.NUMFAT = A1.NUMFAT AND B.DTFAT = A1.DTFAT AND B.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S') AS TIPOAVVISO,
         COALESCE(A.TOTFAT - 
          (SELECT SUM( CASE WHEN CODIVA1 = '3945' THEN IMPONI1
            ELSE (CASE WHEN CODIVA2 = '3945' THEN IMPONI2
                ELSE (CASE WHEN CODIVA3 = '3945' THEN IMPONI3
                    ELSE (CASE WHEN CODIVA4 = '3945' THEN IMPONI4
                    ELSE (CASE WHEN CODIVA5 = '3945' THEN IMPONI5
                    ELSE (CASE WHEN CODIVA6 = '3945' THEN IMPONI6
                    ELSE (CASE WHEN CODIVA7 = '3945' THEN IMPONI7
                    ELSE (CASE WHEN CODIVA8 = '3945' THEN IMPONI8
                    ELSE 0 END)END)END)END)END)END)END)END)
             FROM SCASSFAT A, M_STFA_M A1
        WHERE A.NUMFAT = B.NUMFAT AND A.DATFAT = B.DTFAT AND A.CODCLI = B.CODCLI
		AND A.NUMFAT = A1.NUMFAT AND A.DATFAT = A1.DTFAT AND A.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S')
		- (SELECT SUM( CASE WHEN CODIVA1 = '3946' THEN IMPONI1
            ELSE (CASE WHEN CODIVA2 = '3946' THEN IMPONI2
                ELSE (CASE WHEN CODIVA3 = '3946' THEN IMPONI3
                    ELSE (CASE WHEN CODIVA4 = '3946' THEN IMPONI4
                    ELSE (CASE WHEN CODIVA5 = '3946' THEN IMPONI5
                    ELSE (CASE WHEN CODIVA6 = '3946' THEN IMPONI6
                    ELSE (CASE WHEN CODIVA7 = '3946' THEN IMPONI7
                    ELSE (CASE WHEN CODIVA8 = '3946' THEN IMPONI8
                    ELSE 0 END)END)END)END)END)END)END)END)
             FROM SCASSFAT A, M_STFA_M A1
        WHERE A.NUMFAT = B.NUMFAT AND A.DATFAT = B.DTFAT AND A.CODCLI = B.CODCLI
		AND A.NUMFAT = A1.NUMFAT AND A.DATFAT = A1.DTFAT AND A.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S')
        - (SELECT SUM( CASE WHEN CODIVA1 = 'TEFA' THEN IMPONI1
            ELSE (CASE WHEN CODIVA2 = 'TEFA' THEN IMPONI2
                ELSE (CASE WHEN CODIVA3 = 'TEFA' THEN IMPONI3
                    ELSE (CASE WHEN CODIVA4 = 'TEFA' THEN IMPONI4
                    ELSE (CASE WHEN CODIVA5 = 'TEFA' THEN IMPONI5
                    ELSE (CASE WHEN CODIVA6 = 'TEFA' THEN IMPONI6
                    ELSE (CASE WHEN CODIVA7 = 'TEFA' THEN IMPONI7
                    ELSE (CASE WHEN CODIVA8 = 'TEFA' THEN IMPONI8
                    ELSE 0 END)END)END)END)END)END)END)END)
             FROM SCASSFAT A, M_STFA_M A1
        WHERE A.NUMFAT = B.NUMFAT AND A.DATFAT = B.DTFAT AND A.CODCLI = B.CODCLI
		AND A.NUMFAT = A1.NUMFAT AND A.DATFAT = A1.DTFAT AND A.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S')
        - (SELECT SUM( CASE WHEN CODIVA1 = 'TEFN' THEN IMPONI1
            ELSE (CASE WHEN CODIVA2 = 'TEFN' THEN IMPONI2
                ELSE (CASE WHEN CODIVA3 = 'TEFN' THEN IMPONI3
                    ELSE (CASE WHEN CODIVA4 = 'TEFN' THEN IMPONI4
                    ELSE (CASE WHEN CODIVA5 = 'TEFN' THEN IMPONI5
                    ELSE (CASE WHEN CODIVA6 = 'TEFN' THEN IMPONI6
                    ELSE (CASE WHEN CODIVA7 = 'TEFN' THEN IMPONI7
                    ELSE (CASE WHEN CODIVA8 = 'TEFN' THEN IMPONI8
                    ELSE 0 END)END)END)END)END)END)END)END)
             FROM SCASSFAT A, M_STFA_M A1
        WHERE A.NUMFAT = B.NUMFAT AND A.DATFAT = B.DTFAT AND A.CODCLI = B.CODCLI
		AND A.NUMFAT = A1.NUMFAT AND A.DATFAT = A1.DTFAT AND A.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S') 
        - (SELECT SUM( CASE WHEN CODIVA1 = 'TEFZ' THEN IMPONI1
            ELSE (CASE WHEN CODIVA2 = 'TEFZ' THEN IMPONI2
                ELSE (CASE WHEN CODIVA3 = 'TEFZ' THEN IMPONI3
                    ELSE (CASE WHEN CODIVA4 = 'TEFZ' THEN IMPONI4
                    ELSE (CASE WHEN CODIVA5 = 'TEFZ' THEN IMPONI5
                    ELSE (CASE WHEN CODIVA6 = 'TEFZ' THEN IMPONI6
                    ELSE (CASE WHEN CODIVA7 = 'TEFZ' THEN IMPONI7
                    ELSE (CASE WHEN CODIVA8 = 'TEFZ' THEN IMPONI8
                    ELSE 0 END)END)END)END)END)END)END)END)
             FROM SCASSFAT A, M_STFA_M A1
        WHERE A.NUMFAT = B.NUMFAT AND A.DATFAT = B.DTFAT AND A.CODCLI = B.CODCLI
		AND A.NUMFAT = A1.NUMFAT AND A.DATFAT = A1.DTFAT AND A.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S') 
        ,0) AS DOVUTO,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.NUMFAT = G.NUMFAT
                    AND B.NUMCONT = G.NUMCONT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE NOT IN ('10','11','14','15','CB','XX')
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                 AND (H.CODTRIB LIKE '%3944%'  OR H.CODTRIB LIKE '%365E%')
            GROUP BY H.CODCLI), 0
        ) AS PAGATO,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.NUMFAT = G.NUMFAT
                    AND B.NUMCONT = G.NUMCONT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE = 'CB'
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                AND (H.CODTRIB LIKE '%3944%'  OR H.CODTRIB LIKE '%365E%')
            GROUP BY H.CODCLI), 0
        ) AS CREDITI_RIPORTATI,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.NUMFAT = G.NUMFAT
                    AND B.NUMCONT = G.NUMCONT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE = 'XX'
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                AND (H.CODTRIB LIKE '%3944%'  OR H.CODTRIB LIKE '%365E%')
            GROUP BY H.CODCLI), 0
        ) AS CREDITI_CHIUSI
    FROM M_STFA_M B
        INNER JOIN SSCADFAT A ON A.CODCLI = B.CODCLI
            AND A.DATFAT = B.DTFAT
            AND A.NUMFAT = B.NUMFAT
	WHERE B.ANNORIF <> '2013'		
    ) AS S1
INNER JOIN FCCLIFAT T ON S1.CODCLI= T.CODCLI AND S1.CODCLI = T.CODCLI  
GROUP BY S1.CODCLI, S1.NUMCONT, S1.ANNORIF, S1.CODICE_TRIBUTO
UNION ALL
SELECT TRIM(S1.CODCLI) CODCLI, TRIM(S1.NUMCONT) NUMCONT, S1.ANNORIF, S1.CODICE_TRIBUTO,
    SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI) as DA_PAGARE,
    case when ((s1.annorif > 2013) or (MAX(s1.tipoavviso) = 'L')) then round( SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI),0)
    ELSE SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI)   end   AS DA_PAGAREN,
    MAX(S1.PAGATO) as PAGATO,
    case when s1.annorif = 2013 then MAX(S1.PAGATO)
    else  round(MAX(S1.PAGATO),0) end  AS PAGATON,
    (SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) AS SALDO,
    case when ((s1.annorif > 2013) or (MAX(s1.tipoavviso) = 'L')) then round((SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) ,0)
    Else (SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) END AS SALDON
FROM
    (SELECT B.CODCLI, B.NUMCONT, '3945' AS CODICE_TRIBUTO, B.ANNORIF AS ANNORIF,

        ( SELECT A1.TIPOAVVISO FROM  M_STFA_M A1
        WHERE B.NUMFAT = A1.NUMFAT AND B.DTFAT = A1.DTFAT AND B.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S') AS TIPOAVVISO,
        COALESCE((SELECT SUM(
            CASE WHEN CODIVA1 = '3945' THEN IMPONI1
            ELSE (
                CASE WHEN CODIVA2 = '3945' THEN IMPONI2
                ELSE (
                    CASE WHEN CODIVA3 = '3945' THEN IMPONI3
                    ELSE (
                    CASE WHEN CODIVA4 = '3945' THEN IMPONI4
                    ELSE (
                    CASE WHEN CODIVA5 = '3945' THEN IMPONI5
                    ELSE (
                    CASE WHEN CODIVA6 = '3945' THEN IMPONI6
                    ELSE (
                    CASE WHEN CODIVA7 = '3945' THEN IMPONI7
                    ELSE (
                    CASE WHEN CODIVA8 = '3945' THEN IMPONI8
                    ELSE 0
                    END)END)END)END)END)END)
               END)
            END)
        FROM SCASSFAT A, M_STFA_M A1
        WHERE A.NUMFAT = B.NUMFAT AND A.DATFAT = B.DTFAT AND A.CODCLI = B.CODCLI
		AND A.NUMFAT = A1.NUMFAT AND A.DATFAT = A1.DTFAT AND A.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S'
        ),0) AS DOVUTO,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.CODCLI = G.CODCLI
                    AND B.NUMCONT = G.NUMCONT
                    AND H.NUMFAT = G.NUMFAT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE NOT IN ('10','11','14','15','CB','XX')
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                AND (H.CODTRIB LIKE '%3945%' OR H.CODTRIB LIKE '%366E%')
            GROUP BY H.CODCLI), 0
        ) AS PAGATO,
            COALESCE(
                (SELECT SUM(H.INCRIM)
                FROM FCAVVPAG H
                    INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                        AND H.NUMFAT = G.NUMFAT
                        AND B.NUMCONT = G.NUMCONT
                        AND H.DATFAT = G.DTFAT
                WHERE H.TIPOCANALE = 'CB'
                    AND G.ANNORIF = B.ANNORIF
                    AND H.CODCLI = B.CODCLI
                    AND (H.CODTRIB LIKE '%3945%' OR H.CODTRIB LIKE '%366E%')
                GROUP BY H.CODCLI), 0
            ) AS CREDITI_RIPORTATI,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.NUMFAT = G.NUMFAT
                    AND B.NUMCONT = G.NUMCONT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE = 'XX'
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                AND (H.CODTRIB LIKE '%3945%' OR H.CODTRIB LIKE '%366E%')
            GROUP BY H.CODCLI), 0
        ) AS CREDITI_CHIUSI
    FROM M_STFA_M B
    INNER JOIN SSCADFAT A ON A.CODCLI = B.CODCLI
        AND A.DATFAT = B.DTFAT
        AND A.NUMFAT = B.NUMFAT
		
    ) AS S1
INNER JOIN FCCLIFAT T ON S1.CODCLI= T.CODCLI AND S1.CODCLI = T.CODCLI 
GROUP BY S1.CODCLI, S1.NUMCONT, S1.ANNORIF, S1.CODICE_TRIBUTO
HAVING SUM(S1.DOVUTO) <> 0 OR MAX(S1.PAGATO) <> 0 
UNION ALL
SELECT TRIM(S1.CODCLI) CODCLI, TRIM(S1.NUMCONT) NUMCONT, S1.ANNORIF, S1.CODICE_TRIBUTO,
    SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI) as DA_PAGARE,
    case when ((s1.annorif > 2013) or (MAX(s1.tipoavviso) = 'L')) then round( SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI),0)
    ELSE SUM(S1.DOVUTO) - MAX(S1.CREDITI_RIPORTATI)   end   AS DA_PAGAREN,
    MAX(S1.PAGATO) as PAGATO,
    case when s1.annorif = 2013 then MAX(S1.PAGATO)
    else  round(MAX(S1.PAGATO),0) end  AS PAGATON,
    (SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) AS SALDO,
    case when ((s1.annorif > 2013) or (MAX(s1.tipoavviso) = 'L')) then round((SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) ,0)
    Else (SUM(S1.DOVUTO) - MAX(S1.PAGATO) - MAX(S1.CREDITI_RIPORTATI) - MAX(S1.CREDITI_CHIUSI)) END AS SALDON
FROM
    (SELECT B.CODCLI, B.NUMCONT, 'TEFA' AS CODICE_TRIBUTO, B.ANNORIF AS ANNORIF,
        ( SELECT COALESCE(A1.TIPOAVVISO,'A') FROM  M_STFA_M A1
        WHERE B.NUMFAT = A1.NUMFAT AND B.DTFAT = A1.DTFAT AND B.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S') AS TIPOAVVISO,
         COALESCE((SELECT SUM(
            CASE WHEN CODIVA1 = 'TEFA' THEN IMPONI1
            ELSE (
                CASE WHEN CODIVA2 = 'TEFA' THEN IMPONI2
                ELSE (
                    CASE WHEN CODIVA3 = 'TEFA' THEN IMPONI3
                    ELSE (
                    CASE WHEN CODIVA4 = 'TEFA' THEN IMPONI4
                    ELSE (
                    CASE WHEN CODIVA5 = 'TEFA' THEN IMPONI5
                    ELSE (
                    CASE WHEN CODIVA6 = 'TEFA' THEN IMPONI6
                    ELSE (
                    CASE WHEN CODIVA7 = 'TEFA' THEN IMPONI7
                    ELSE (
                    CASE WHEN CODIVA8 = 'TEFA' THEN IMPONI8
                    ELSE 0
                    END)END)END)END)END)END)
               END)
            END)
        FROM SCASSFAT A, M_STFA_M A1
        WHERE A.NUMFAT = B.NUMFAT AND A.DATFAT = B.DTFAT AND A.CODCLI = B.CODCLI
		AND A.NUMFAT = A1.NUMFAT AND A.DATFAT = A1.DTFAT AND A.CODCLI = A1.CODCLI
		AND COALESCE(A1.FNT,'N') <> 'S'
        ),0) AS DOVUTO,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.CODCLI = G.CODCLI
                    AND B.NUMCONT = G.NUMCONT
                    AND H.NUMFAT = G.NUMFAT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE NOT IN ('10','11','14','15','CB','XX')
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                AND H.CODTRIB LIKE '%TEFA%'
            GROUP BY H.CODCLI), 0
        ) AS PAGATO,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.NUMFAT = G.NUMFAT
                    AND B.NUMCONT = G.NUMCONT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE = 'CB'
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                AND H.CODTRIB LIKE '%TEFA%'
            GROUP BY H.CODCLI), 0
        ) AS CREDITI_RIPORTATI,
        COALESCE(
            (SELECT SUM(H.INCRIM)
            FROM FCAVVPAG H
                INNER JOIN M_STFA_M G ON H.CODCLI = G.CODCLI
                    AND H.NUMFAT = G.NUMFAT
                    AND B.NUMCONT = G.NUMCONT
                    AND H.DATFAT = G.DTFAT
            WHERE H.TIPOCANALE = 'XX'
                AND G.ANNORIF = B.ANNORIF
                AND H.CODCLI = B.CODCLI
                AND H.CODTRIB LIKE '%TEFA%'
            GROUP BY H.CODCLI), 0
        ) AS CREDITI_CHIUSI
    FROM M_STFA_M B
    INNER JOIN SSCADFAT A ON A.CODCLI = B.CODCLI
        AND A.DATFAT = B.DTFAT
        AND A.NUMFAT = B.NUMFAT		
    ) AS S1
INNER JOIN FCCLIFAT T ON S1.CODCLI= T.CODCLI AND S1.CODCLI = T.CODCLI 
GROUP BY S1.CODCLI, S1.NUMCONT, S1.ANNORIF, S1.CODICE_TRIBUTO
HAVING SUM(S1.DOVUTO) <> 0 OR MAX(S1.PAGATO) <> 0 OR MAX(S1.CREDITI_RIPORTATI) <> 0 ) A
INNER JOIN 
(SELECT
TRIM(CODCLI) CODCLI,TRIM(NUMCONT) NUMCONT,RAGSO,INDIRIZZO,CF,TIPDOC,STORNO,ANNORIF,MAX(DTFAT) DTFAT,MAX(NUMFAT) NUMFAT,
CASE WHEN ANNOF>2021 THEN MAX(NUMFAT) ELSE CONCAT('F965-',MAX(CAST(NUMFAT AS int)),'-',ANNOF) END NUM_AVVISO
FROM
(SELECT 
CODCLI,
NUMCONT,
CONCAT(TRIM(RAGSOC),' ',TRIM(RAGSO2)) RAGSO,
CONCAT(TRIM(INDIR),CASE WHEN TRIM(CAP)='' THEN '' ELSE ' - ' END,TRIM(CAP)) INDIRIZZO,
PIVA CF,
NUMFAT,
DTFAT,
TIPDOC,
FNT STORNO,
ANNORIF,
ANNOF
FROM M_STFA_M
where FNT='N' AND TIPDOC='F')A
GROUP BY CODCLI,NUMCONT,RAGSO,INDIRIZZO,CF,TIPDOC,STORNO,ANNORIF,ANNOF
)B ON A.CODCLI=B.CODCLI AND A.ANNORIF=B.ANNORIF
