SELECT CONCAT(TRIM(A.VIA),', ',TRIM(A.NUMCIV),' - ',TRIM(A.CITTA),', ',TRIM(A.CAP),' (',TRIM(A.PROV),')') Indirizzo
	FROM (
		SELECT * FROM (
		SELECT CODCLI,VIA,CAP,CITTA,NUMCIV,PROV,PRGCLI,RAGSO3,
		RANK() OVER (PARTITION BY CODCLI ORDER BY PRGCLI DESC) N
		FROM [20.82.75.6].TARI.dbo.{0}FCCLISED) M WHERE N=1
	) A
	where A.CODCLI='{1}'