// <auto-generated />
using System;
using GaCloudServer.Admin.EntityFramework.Shared.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaCloudServer.Admin.EntityFramework.SqlServer.Migrations.Resources
{
    [DbContext(typeof(ResourcesDbContext))]
    [Migration("20220914064648_GaMezzi")]
    partial class GaMezzi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniAllegato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("AutorizzazioniDocumentoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorizzazioniDocumentoId");

                    b.ToTable("GaAutorizzazioniAllegati");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Archiviata")
                        .HasColumnType("bit");

                    b.Property<long>("AutorizzazioniTipoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataRilascio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Preavviso")
                        .HasColumnType("int");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorizzazioniTipoId");

                    b.ToTable("GaAutorizzazioniDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniTipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaAutorizzazioniTipi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.Views.ViewGaAutorizzazioniDocumenti", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Archiviata")
                        .HasColumnType("bit");

                    b.Property<string>("AutorizzazioniTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRilascio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaAutorizzazioniDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Centro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GaCdrCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Imm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pericoloso")
                        .HasColumnType("bit");

                    b.Property<bool>("Peso")
                        .HasColumnType("bit");

                    b.Property<bool>("Qta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaCdrCers");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerDettaglio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CdrCerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<int>("PesoDefault")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CdrCerId");

                    b.ToTable("GaCdrCersDettagli");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerOnCentro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CdrCentroId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrCerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CdrCentroId")
                        .IsUnique();

                    b.HasIndex("CdrCerId");

                    b.ToTable("GaCdrCersOnCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComune", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaCdrComuni");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComuneOnCentro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CdrCentroId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrComuneId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CdrCentroId");

                    b.HasIndex("CdrComuneId");

                    b.ToTable("GaCdrComuniOnCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Comunicati.ComunicatiDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titolo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GaComunicatiDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziAlimentazione", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziAlimentazioni");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziCantiere", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziCantieri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziClasse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziClassi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezziVeicoloId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MezziVeicoloId");

                    b.ToTable("GaMezziDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPatente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziPatenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPeriodoScadenza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziPeriodiScadenze");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziProprietario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziProprietari");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezziScadenzaTipoId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziVeicoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MezziScadenzaTipoId");

                    b.HasIndex("MezziVeicoloId");

                    b.ToTable("GaMezziScadenze");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenzaTipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziScadenzeTipi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziTipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziTipi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AlboGestori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnnoImmatricolazione")
                        .HasColumnType("int");

                    b.Property<string>("Attrezzatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CatalogoRicambi")
                        .HasColumnType("bit");

                    b.Property<bool>("Ce")
                        .HasColumnType("bit");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Dismesso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DismessoData")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Garanzia")
                        .HasColumnType("bit");

                    b.Property<bool>("ManualeUsoManutenzione")
                        .HasColumnType("bit");

                    b.Property<int>("MassaKg")
                        .HasColumnType("int");

                    b.Property<long>("MezziAlimentazioneId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziCantiereId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziClasseId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziPatenteId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziPeriodoScadenzaId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziProprietarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziTipoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelaio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortataKg")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScadenzaContratto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargaPrecedente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MezziAlimentazioneId");

                    b.HasIndex("MezziCantiereId");

                    b.HasIndex("MezziClasseId");

                    b.HasIndex("MezziPatenteId");

                    b.HasIndex("MezziPeriodoScadenzaId");

                    b.HasIndex("MezziProprietarioId");

                    b.HasIndex("MezziTipoId");

                    b.ToTable("GaMezziVeicoli");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.Views.ViewGaMezziDocumenti", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezzoVeicoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaMezziDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.Views.ViewGaMezziScadenze", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cantiere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Dismesso")
                        .HasColumnType("bit");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezzoVeicoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoScadenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoScadenza")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaMezziScadenze");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.Views.ViewGaMezziVeicoli", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AlboGestori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlimentazioneMezzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnnoImmatricolazione")
                        .HasColumnType("int");

                    b.Property<bool>("CDP")
                        .HasColumnType("bit");

                    b.Property<bool>("CDPD")
                        .HasColumnType("bit");

                    b.Property<string>("CantiereMezzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CatalogoRicambi")
                        .HasColumnType("bit");

                    b.Property<bool>("Ce")
                        .HasColumnType("bit");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Dismesso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DismessoData")
                        .HasColumnType("datetime2");

                    b.Property<string>("EuroMezzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Garanzia")
                        .HasColumnType("bit");

                    b.Property<bool>("ManualeUsoManutenzione")
                        .HasColumnType("bit");

                    b.Property<int>("MassaKg")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelaio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatenteMezzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortataKg")
                        .HasColumnType("int");

                    b.Property<string>("ProprietaMezzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScadenzaContratto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMezzo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaMezziVeicoli");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniAllegato", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniDocumento", "AutorizzazioniDocumento")
                        .WithMany()
                        .HasForeignKey("AutorizzazioniDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorizzazioniDocumento");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniDocumento", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniTipo", "AutorizzazioniTipo")
                        .WithMany()
                        .HasForeignKey("AutorizzazioniTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorizzazioniTipo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerDettaglio", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", "CdrCer")
                        .WithMany()
                        .HasForeignKey("CdrCerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCer");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerOnCentro", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", "CdrCentro")
                        .WithOne("CdrCerOnCentro")
                        .HasForeignKey("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerOnCentro", "CdrCentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", "CdrCer")
                        .WithMany()
                        .HasForeignKey("CdrCerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCentro");

                    b.Navigation("CdrCer");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComuneOnCentro", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", "CdrCentro")
                        .WithMany("CdrComuniOnCentri")
                        .HasForeignKey("CdrCentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComune", "CdrComune")
                        .WithMany()
                        .HasForeignKey("CdrComuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCentro");

                    b.Navigation("CdrComune");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziDocumento", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", "MezziVeicolo")
                        .WithMany()
                        .HasForeignKey("MezziVeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MezziVeicolo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenza", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenzaTipo", "MezziScadenzaTipo")
                        .WithMany()
                        .HasForeignKey("MezziScadenzaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", "MezziVeicolo")
                        .WithMany()
                        .HasForeignKey("MezziVeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MezziScadenzaTipo");

                    b.Navigation("MezziVeicolo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziAlimentazione", "MezziAlimentazione")
                        .WithMany()
                        .HasForeignKey("MezziAlimentazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziCantiere", "MezziCantiere")
                        .WithMany()
                        .HasForeignKey("MezziCantiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziClasse", "MezziClasse")
                        .WithMany()
                        .HasForeignKey("MezziClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPatente", "MezziPatente")
                        .WithMany()
                        .HasForeignKey("MezziPatenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPeriodoScadenza", "MezziPeriodoScadenza")
                        .WithMany()
                        .HasForeignKey("MezziPeriodoScadenzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziProprietario", "MezziProprietario")
                        .WithMany()
                        .HasForeignKey("MezziProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziTipo", "MezziTipo")
                        .WithMany()
                        .HasForeignKey("MezziTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MezziAlimentazione");

                    b.Navigation("MezziCantiere");

                    b.Navigation("MezziClasse");

                    b.Navigation("MezziPatente");

                    b.Navigation("MezziPeriodoScadenza");

                    b.Navigation("MezziProprietario");

                    b.Navigation("MezziTipo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", b =>
                {
                    b.Navigation("CdrCerOnCentro");

                    b.Navigation("CdrComuniOnCentri");
                });
#pragma warning restore 612, 618
        }
    }
}
