// <auto-generated />
using System;
using GaCloudServer.Admin.EntityFramework.Shared.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GaCloudServer.Admin.EntityFramework.SqlServer.Migrations.Resources
{
    [DbContext(typeof(ResourcesDbContext))]
    [Migration("20220927105911_SpGaBackOffice")]
    partial class SpGaBackOffice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniAllegato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("AutorizzazioniDocumentoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorizzazioniDocumentoId");

                    b.ToTable("GaAutorizzazioniAllegati");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Archiviata")
                        .HasColumnType("bit");

                    b.Property<long>("AutorizzazioniTipoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataRilascio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Preavviso")
                        .HasColumnType("int");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorizzazioniTipoId");

                    b.ToTable("GaAutorizzazioniDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniTipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaAutorizzazioniTipi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.Views.ViewGaAutorizzazioniDocumenti", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Archiviata")
                        .HasColumnType("bit");

                    b.Property<string>("AutorizzazioniTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRilascio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaAutorizzazioniDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Aziende.AziendeLista", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaAziendeListe");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.BackOfficeParametroOnCategoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<double>("Kc")
                        .HasColumnType("float");

                    b.Property<double>("Kd")
                        .HasColumnType("float");

                    b.Property<double>("KgMqAnnui")
                        .HasColumnType("float");

                    b.Property<double>("KgMqRecupero")
                        .HasColumnType("float");

                    b.Property<double>("KgMqRecuperoGg")
                        .HasColumnType("float");

                    b.Property<double>("KgMqSmaltimento")
                        .HasColumnType("float");

                    b.Property<double>("KgMqSmaltimentoGg")
                        .HasColumnType("float");

                    b.Property<int>("NumeroSvuotamenti")
                        .HasColumnType("int");

                    b.Property<double>("PercentualeCarta")
                        .HasColumnType("float");

                    b.Property<double>("PercentualePlastica")
                        .HasColumnType("float");

                    b.Property<double>("PercentualeUmido")
                        .HasColumnType("float");

                    b.Property<double>("PercentualeVetro")
                        .HasColumnType("float");

                    b.Property<double>("TFissa")
                        .HasColumnType("float");

                    b.Property<double>("TVarCalcolata")
                        .HasColumnType("float");

                    b.Property<double>("TVarMisurata")
                        .HasColumnType("float");

                    b.Property<string>("TipoId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GaBackOfficeParametriOnCategorie");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.BackOfficeStatoTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaBackOfficeStatiTickets");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.BackOfficeTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BackOfficeStatoTicketId")
                        .HasColumnType("bigint");

                    b.Property<long>("BackOfficeTipoTicketId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Note1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BackOfficeStatoTicketId");

                    b.HasIndex("BackOfficeTipoTicketId");

                    b.ToTable("GaBackOfficeTickets");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.BackOfficeTipoTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaBackOfficeTipiTickets");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Sp.SpGaBackOfficeLettureEmz", b =>
                {
                    b.Property<string>("Calotta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodComune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataConferimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesCat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispositivoAssociato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indenti1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Lt")
                        .HasColumnType("float");

                    b.Property<int?>("NrComp")
                        .HasColumnType("int");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OraSvuotamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tributo")
                        .HasColumnType("nvarchar(max)");

                    b.ToView(null);
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Sp.SpGaBackOfficeLettureMezzi", b =>
                {
                    b.Property<string>("Cat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodComune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataConferimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesCat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescAnomalia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indenti1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Lt")
                        .HasColumnType("float");

                    b.Property<string>("MaterialeLettoDaAnagrafica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NrComp")
                        .HasColumnType("int");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OraSvuotamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServizioIdentificativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tributo")
                        .HasColumnType("nvarchar(max)");

                    b.ToView(null);
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Sp.SpGaBackOfficeUtenzeContenitori", b =>
                {
                    b.Property<string>("Cessato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CpRowNum")
                        .HasColumnType("int");

                    b.Property<string>("DesCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identi1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lt")
                        .HasColumnType("float");

                    b.Property<string>("NumCiv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrgCon")
                        .HasColumnType("int");

                    b.Property<string>("RagCli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipCon")
                        .HasColumnType("nvarchar(max)");

                    b.ToView(null);
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Views.ViewGaBackOfficeCategorie", b =>
                {
                    b.Property<string>("Categ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesTar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Domest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tributo")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ViewGaBackOfficeCategorie");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Views.ViewGaBackOfficeComuni", b =>
                {
                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.ToView("ViewGaBackOfficeComuni");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Views.ViewGaBackOfficeNdUtenze", b =>
                {
                    b.Property<string>("Barrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Civico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodAzi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodZona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Decorrenza")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesIstat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Interno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Istat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagCli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Superfic")
                        .HasColumnType("float");

                    b.ToView("ViewGaBackOfficeNdUtenze");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Views.ViewGaBackOfficeNdUtenzeGrouped", b =>
                {
                    b.Property<string>("Civico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodAzi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodZona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagCli")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ViewGaBackOfficeNdUtenzeGrouped");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.Views.ViewGaBackOfficeUtenzeGrouped", b =>
                {
                    b.Property<string>("Civico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodAzi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodCom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodFis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodZona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Domest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagCli")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ViewGaBackOfficeUtenzeGrouped");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Centro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserMail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GaCdrCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Imm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pericoloso")
                        .HasColumnType("bit");

                    b.Property<bool>("Peso")
                        .HasColumnType("bit");

                    b.Property<bool>("Qta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaCdrCers");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerDettaglio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CdrCerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<int>("PesoDefault")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CdrCerId");

                    b.ToTable("GaCdrCersDettagli");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerOnCentro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CdrCentroId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrCerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CdrCentroId")
                        .IsUnique();

                    b.HasIndex("CdrCerId");

                    b.ToTable("GaCdrCersOnCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComune", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaCdrComuni");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComuneOnCentro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CdrCentroId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrComuneId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CdrCentroId");

                    b.HasIndex("CdrComuneId");

                    b.ToTable("GaCdrComuniOnCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrConferimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Anagrafica")
                        .HasColumnType("bit");

                    b.Property<long>("CdrCentroId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrCerDettaglioId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrCerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CdrComuneId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CdrUtenteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfPiva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Ditta")
                        .HasColumnType("bit");

                    b.Property<bool>("Noleggio")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CdrCentroId");

                    b.HasIndex("CdrCerDettaglioId");

                    b.HasIndex("CdrCerId");

                    b.ToTable("GaCdrConferimenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrRichiestaViaggio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CdrCentroId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrCerId")
                        .HasColumnType("bigint");

                    b.Property<long>("CdrStatoRichiestaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Inviata")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PesoDestino")
                        .HasColumnType("float");

                    b.Property<double>("PesoPresunto")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CdrCerId");

                    b.HasIndex("CdrStatoRichiestaId");

                    b.ToTable("GaCdrRichiesteViaggi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrStatoRichiesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaCdrStatiRichieste");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrUtente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Approvato")
                        .HasColumnType("bit");

                    b.Property<long>("CdrComuneId")
                        .HasColumnType("bigint");

                    b.Property<string>("CfPiva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Ditta")
                        .HasColumnType("bit");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InserimentoUtente")
                        .HasColumnType("bit");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CdrComuneId");

                    b.ToTable("GaCdrUtenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.Views.ViewGaCdrCersOnCentri", b =>
                {
                    b.Property<bool>("Abilitato")
                        .HasColumnType("bit");

                    b.Property<long>("CentroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.ToView("ViewGaCdrCersOnCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.Views.ViewGaCdrComuni", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToView("ViewGaCdrComuni");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.Views.ViewGaCdrComuniOnCentri", b =>
                {
                    b.Property<bool>("Abilitato")
                        .HasColumnType("bit");

                    b.Property<long>("CentroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ComuneId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.ToView("ViewGaCdrComuniOnCentri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.Views.ViewGaCdrConferimenti", b =>
                {
                    b.Property<string>("CdrUtenteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Centro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CerDettaglio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfPiva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumCon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteRegistrazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imm")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ViewGaCdrConferimenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.Views.ViewGaCdrRichiesteViaggi", b =>
                {
                    b.Property<string>("Centro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CentroId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Imm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inviata")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<double>("PesoDestino")
                        .HasColumnType("float");

                    b.Property<double>("PesoPresunto")
                        .HasColumnType("float");

                    b.Property<string>("Richiedente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatoRichiesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StatoRichiestaId")
                        .HasColumnType("bigint");

                    b.ToView("ViewGaCdrRichiesteViaggi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.Views.ViewGaCdrUtenti", b =>
                {
                    b.Property<string>("Approvato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CfPiva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Ditta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Indirizzo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InserimentoUtente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ViewGaCdrUtenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Comunicati.ComunicatiDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDocumento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titolo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GaComunicatiDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.ContrattiPermesso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaContrattiPermessi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.ContrattiServizio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaContrattiServizi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.ContrattiTipologia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaContrattiTipologie");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.ContrattiUtenteOnPermesso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ContrattiPermessoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("UtenteId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContrattiPermessoId");

                    b.ToTable("GaContrattiUtentiOnPermessi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.Views.ViewGaContrattiUtenti", b =>
                {
                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteId")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ViewGaContrattiUtenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.Views.ViewGaContrattiUtentiOnPermessi", b =>
                {
                    b.Property<bool>("Abilitato")
                        .HasColumnType("bit");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Permesso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PermessoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Utente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtenteId")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ViewGaContrattiUtentiOnPermessi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziAlimentazione", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziAlimentazioni");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziCantiere", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziCantieri");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziClasse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziClassi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziDocumento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezziVeicoloId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MezziVeicoloId");

                    b.ToTable("GaMezziDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPatente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziPatenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPeriodoScadenza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziPeriodiScadenze");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziProprietario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziProprietari");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenza", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezziScadenzaTipoId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziVeicoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MezziScadenzaTipoId");

                    b.HasIndex("MezziVeicoloId");

                    b.ToTable("GaMezziScadenze");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenzaTipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziScadenzeTipi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziTipo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GaMezziTipi");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AlboGestori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnnoImmatricolazione")
                        .HasColumnType("int");

                    b.Property<string>("Attrezzatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CatalogoRicambi")
                        .HasColumnType("bit");

                    b.Property<bool>("Ce")
                        .HasColumnType("bit");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Dismesso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DismessoData")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Garanzia")
                        .HasColumnType("bit");

                    b.Property<bool>("ManualeUsoManutenzione")
                        .HasColumnType("bit");

                    b.Property<int>("MassaKg")
                        .HasColumnType("int");

                    b.Property<long>("MezziAlimentazioneId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziCantiereId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziClasseId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziPatenteId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziPeriodoScadenzaId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziProprietarioId")
                        .HasColumnType("bigint");

                    b.Property<long>("MezziTipoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelaio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortataKg")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScadenzaContratto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargaPrecedente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MezziAlimentazioneId");

                    b.HasIndex("MezziCantiereId");

                    b.HasIndex("MezziClasseId");

                    b.HasIndex("MezziPatenteId");

                    b.HasIndex("MezziPeriodoScadenzaId");

                    b.HasIndex("MezziProprietarioId");

                    b.HasIndex("MezziTipoId");

                    b.ToTable("GaMezziVeicoli");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.Views.ViewGaMezziDocumenti", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezziVeicoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaMezziDocumenti");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.Views.ViewGaMezziScadenze", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Cantiere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Dismesso")
                        .HasColumnType("bit");

                    b.Property<string>("FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MezziVeicoloId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoScadenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoScadenza")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaMezziScadenze");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.Views.ViewGaMezziVeicoli", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AlboGestori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alimentazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnnoImmatricolazione")
                        .HasColumnType("int");

                    b.Property<bool>("CDP")
                        .HasColumnType("bit");

                    b.Property<bool>("CDPD")
                        .HasColumnType("bit");

                    b.Property<string>("Cantiere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CatalogoRicambi")
                        .HasColumnType("bit");

                    b.Property<bool>("Ce")
                        .HasColumnType("bit");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Dismesso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DismessoData")
                        .HasColumnType("datetime2");

                    b.Property<string>("Euro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Garanzia")
                        .HasColumnType("bit");

                    b.Property<bool>("ManualeUsoManutenzione")
                        .HasColumnType("bit");

                    b.Property<int>("MassaKg")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelaio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortataKg")
                        .HasColumnType("int");

                    b.Property<string>("Proprietario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScadenzaContratto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Targa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToView("ViewGaMezziVeicoli");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniAllegato", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniDocumento", "AutorizzazioniDocumento")
                        .WithMany()
                        .HasForeignKey("AutorizzazioniDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorizzazioniDocumento");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniDocumento", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Autorizzazioni.AutorizzazioniTipo", "AutorizzazioniTipo")
                        .WithMany()
                        .HasForeignKey("AutorizzazioniTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AutorizzazioniTipo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.BackOfficeTicket", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.BackOfficeStatoTicket", "BackOfficeStatoTicket")
                        .WithMany()
                        .HasForeignKey("BackOfficeStatoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.BackOffice.BackOfficeTipoTicket", "BackOfficeTipoTicket")
                        .WithMany()
                        .HasForeignKey("BackOfficeTipoTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackOfficeStatoTicket");

                    b.Navigation("BackOfficeTipoTicket");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerDettaglio", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", "CdrCer")
                        .WithMany()
                        .HasForeignKey("CdrCerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCer");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerOnCentro", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", "CdrCentro")
                        .WithOne("CdrCerOnCentro")
                        .HasForeignKey("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerOnCentro", "CdrCentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", "CdrCer")
                        .WithMany()
                        .HasForeignKey("CdrCerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCentro");

                    b.Navigation("CdrCer");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComuneOnCentro", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", "CdrCentro")
                        .WithMany("CdrComuniOnCentri")
                        .HasForeignKey("CdrCentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComune", "CdrComune")
                        .WithMany()
                        .HasForeignKey("CdrComuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCentro");

                    b.Navigation("CdrComune");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrConferimento", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", "CdrCentro")
                        .WithMany()
                        .HasForeignKey("CdrCentroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCerDettaglio", "CdrCerDettaglio")
                        .WithMany()
                        .HasForeignKey("CdrCerDettaglioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", "CdrCer")
                        .WithMany()
                        .HasForeignKey("CdrCerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCentro");

                    b.Navigation("CdrCer");

                    b.Navigation("CdrCerDettaglio");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrRichiestaViaggio", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCer", "CdrCer")
                        .WithMany()
                        .HasForeignKey("CdrCerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrStatoRichiesta", "CdrStatoRichiesta")
                        .WithMany()
                        .HasForeignKey("CdrStatoRichiestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrCer");

                    b.Navigation("CdrStatoRichiesta");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrUtente", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrComune", "CdrComune")
                        .WithMany()
                        .HasForeignKey("CdrComuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CdrComune");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.ContrattiUtenteOnPermesso", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Contratti.ContrattiPermesso", "ContrattiPermesso")
                        .WithMany()
                        .HasForeignKey("ContrattiPermessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContrattiPermesso");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziDocumento", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", "MezziVeicolo")
                        .WithMany()
                        .HasForeignKey("MezziVeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MezziVeicolo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenza", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziScadenzaTipo", "MezziScadenzaTipo")
                        .WithMany()
                        .HasForeignKey("MezziScadenzaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", "MezziVeicolo")
                        .WithMany()
                        .HasForeignKey("MezziVeicoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MezziScadenzaTipo");

                    b.Navigation("MezziVeicolo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziVeicolo", b =>
                {
                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziAlimentazione", "MezziAlimentazione")
                        .WithMany()
                        .HasForeignKey("MezziAlimentazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziCantiere", "MezziCantiere")
                        .WithMany()
                        .HasForeignKey("MezziCantiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziClasse", "MezziClasse")
                        .WithMany()
                        .HasForeignKey("MezziClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPatente", "MezziPatente")
                        .WithMany()
                        .HasForeignKey("MezziPatenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziPeriodoScadenza", "MezziPeriodoScadenza")
                        .WithMany()
                        .HasForeignKey("MezziPeriodoScadenzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziProprietario", "MezziProprietario")
                        .WithMany()
                        .HasForeignKey("MezziProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Mezzi.MezziTipo", "MezziTipo")
                        .WithMany()
                        .HasForeignKey("MezziTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MezziAlimentazione");

                    b.Navigation("MezziCantiere");

                    b.Navigation("MezziClasse");

                    b.Navigation("MezziPatente");

                    b.Navigation("MezziPeriodoScadenza");

                    b.Navigation("MezziProprietario");

                    b.Navigation("MezziTipo");
                });

            modelBuilder.Entity("GaCloudServer.Admin.EntityFramework.Shared.Entities.Resources.Cdr.CdrCentro", b =>
                {
                    b.Navigation("CdrCerOnCentro");

                    b.Navigation("CdrComuniOnCentri");
                });
#pragma warning restore 612, 618
        }
    }
}
