DROP VIEW [dbo].[ViewConsorzioProduttori]
DROP VIEW [dbo].[ViewConsorzioDestinatari]
DROP VIEW [dbo].[ViewConsorzioTrasportatori]
DROP VIEW [dbo].[ViewConsorzioExportSingoli]
DROP VIEW [dbo].[ViewConsorzioCers]
DROP VIEW [dbo].[ViewConsorzioRegistrazioni]