USE [GaCloud]
GO

/****** Object:  View [dbo].[BiViewBackOfficeTariInsolutoNovi]    Script Date: 11/03/2024 15:58:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW ViewGaBackOfficeUtenzeNovi
AS
SELECT 
CAST(0 AS BIGINT) Id,
A.CodCli,
CONCAT(TRIM(RAGSO1),' ',TRIM(RAGSO2)) RagSo,
CodFis,
Citta,
Via,
NumCiv,
B.NumCon,
ISNULL(C.CONTA,0) PrintCount,
CAST (0 AS BIT) Disabled
FROM [20.82.75.6].[TARI].[dbo].[C19FCCLIFAT] A
INNER JOIN [20.82.75.6].[TARI].[dbo].C19M_TSCON B ON A.CODCLI=B.CODCOM
LEFT OUTER JOIN (SELECT CODCLI,NUMCON,COUNT(*) CONTA FROM GaBackOfficeRecipes GROUP BY CODCLI,NUMCON) C ON A.CodCli=C.CodCli COLLATE DATABASE_DEFAULT AND B.NUMCON=C.NumCon COLLATE DATABASE_DEFAULT
GO
