SELECT DTREG AS DataRegistrazione,
DATFAT AS DataDocumento,
CONCAT('RITENUTA D''ACCONTO SU FATTURA ',TRIM(NUMFAT), ' DEL ',FORMAT(DATFAT,'ddMMyyyy','it-IT')) DescrizioneMovimento,
'AC02400014' ContoClienteFornitore,
FORMAT(INCRIM, 'F2', 'it-IT') AS TotaleOperazione,
DT_AVPAG DataValuta,
ISNULL(C.ContoNeta,'') ContoPagamento,
A.DT_AVPAG DataPagamento,
CONCAT(A.CODCLI,' - ',A.RAGSOC) Nota,
NumFat,
A.RAGSOC,A.CODCLI,A.CONTOC,A.TIPOCANALE,CONCAT(TRIM(A.CODCLI),FORMAT(DTREG,'yyyyMMdd','it-IT'),FORMAT(A.DT_AVPAG,'yyyyMMdd','it-IT'),TRIM(NUMFAT),FORMAT(A.DATFAT,'yyyyMMdd','it-IT'),A.TIPOCANALE,'RITE') UniqueKey 
FROM (SELECT A.*,B.RAGSOC,B.PIVA FROM (SELECT * FROM [20.82.75.6].TARI.dbo.C90FCAVVPAG WHERE TIPOCANALE IN ('RA')) A 
INNER JOIN [20.82.75.6].TARI.dbo.C90M_STFA_M B ON A.CODCLI=B.CODCLI AND A.NUMFAT=B.NUMFAT AND A.DATFAT=B.DTFAT) A 
LEFT OUTER JOIN GaCreDebConti B ON A.PIVA=B.CodFis COLLATE DATABASE_DEFAULT 
LEFT OUTER JOIN GaCreDebCanali C ON A.TIPOCANALE=C.CodCanale COLLATE DATABASE_DEFAULT 
WHERE DTREG>='{0}' AND (DT_AVPAG BETWEEN '{1}' AND '{2}') --AND TRIM(A.CODCLI)='02168'
AND CONCAT(TRIM(A.CODCLI),FORMAT(DTREG,'yyyyMMdd','it-IT'),FORMAT(A.DT_AVPAG,'yyyyMMdd','it-IT'),TRIM(NUMFAT),FORMAT(A.DATFAT,'yyyyMMdd','it-IT'),A.TIPOCANALE,'RITE') COLLATE DATABASE_DEFAULT NOT IN
(SELECT UniqueKey FROM GaCreDebObjectDetails A INNER JOIN GaCreDebObjects B ON A.IdTask=B.Id WHERE B.Contab=1)