SELECT DT_AVPAG AS DataRegistrazione,
DATFAT AS DataDocumento,
CONCAT(CASE WHEN A.TIPOCANALE IN ('GA','G1','G2') THEN 'ANTICIPO IN DATA ' ELSE 'INCASSO IN DATA ' END,FORMAT(DT_AVPAG,'dd/MM/yyyy','it-IT'),' SU FATTURA ',TRIM(NUMFAT), ' DEL ',FORMAT(DATFAT,'ddMMyyyy','it-IT')) DescrizioneMovimento,
ISNULL(B.ContoNeta,'AC02007817') ContoClienteFornitore,
FORMAT(INCRIM, 'F2', 'it-IT') AS TotaleOperazione,
DT_AVPAG DataValuta,
ISNULL(C.ContoNeta,'') ContoPagamento,
A.DT_AVPAG DataPagamento,
CONCAT(A.CODCLI,' - ',A.RAGSOC) Nota,
NumFat,
A.RAGSOC RagSoc,A.CODCLI CodCli,A.CONTOC ContoC,A.TIPOCANALE Canale,CONCAT(TRIM(A.CODCLI),FORMAT(DTREG,'yyyyMMdd','it-IT'),FORMAT(A.DT_AVPAG,'yyyyMMdd','it-IT'),TRIM(NUMFAT),FORMAT(A.DATFAT,'yyyyMMdd','it-IT'),A.TIPOCANALE) UniqueKey 
FROM (SELECT A.*,B.RAGSOC,B.PIVA FROM (SELECT * FROM [20.82.75.6].TARI.dbo.C90FCAVVPAG WHERE TIPOCANALE IN (SELECT CodCanale COLLATE DATABASE_DEFAULT FROM GaCreDebCanali WHERE Exclude=0)) A 
INNER JOIN [20.82.75.6].TARI.dbo.C90M_STFA_M B ON A.CODCLI=B.CODCLI AND A.NUMFAT=B.NUMFAT AND A.DATFAT=B.DTFAT) A 
LEFT OUTER JOIN GaCreDebConti B ON A.PIVA=B.CodFis COLLATE DATABASE_DEFAULT 
LEFT OUTER JOIN GaCreDebCanali C ON A.TIPOCANALE=C.CodCanale COLLATE DATABASE_DEFAULT 
WHERE DTREG>='{0}' AND (DT_AVPAG BETWEEN '{1}' AND '{2}') AND  
CONCAT(TRIM(A.CODCLI),FORMAT(DTREG,'yyyyMMdd','it-IT'),FORMAT(A.DT_AVPAG,'yyyyMMdd','it-IT'),TRIM(NUMFAT),FORMAT(A.DATFAT,'yyyyMMdd','it-IT'),A.TIPOCANALE) COLLATE DATABASE_DEFAULT NOT IN 
(SELECT UniqueKey FROM GaCreDebObjectDetails A INNER JOIN GaCreDebObjects B ON A.IdTask=B.Id WHERE B.Contab=1)
